//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace таблица_лаба_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lizing
    {
        public int ID { get; set; }
        public string Фамилия { get; set; }
        public int Автомобиль { get; set; }
        public string Контакты { get; set; }
    
        public virtual Auto Auto { get; set; }
    }
}
